### PR TITLE
Load configuration from .reek.yml

### PR DESCRIPTION
**Pull request by parruda**
The plugin is currently not loading the config from a `.reek.yml` you may have in your project. Looking at Reek's source I found the method `::Reek::Configuration::AppConfiguration.from_default_path`.

I tested locally and it worked.

### CODE REVIEW

**Comment by cj** [comment]
@parruda I tried this patch, but it still is not picking up my custom .reek.yml config, I tried adding the config to my app directory and home path.

**Comment by nomasprime** [comment]
@castwide resuming thread from [misfiled issue](https://github.com/castwide/solargraph/issues/388).

@parruda thanks for patch. Unfortunately not working for me either.

**Comment by tommyalvarez** [comment]
@castwide any update on this one?

**Comment by basabin54** [comment]
Not sure if anyone is still looking into this issue or not, but I have been doing a bunch of testing today, and this PR does work, but doesn't solve 100% of the problems.

It does pull in .reek.yml file, but it looks like there might be a bug in Reek itself in how that file is then interpreted by the Examiner constructor because smells are still returned for files that should be excluded in the "directories:" section of the yml file. The global detector settings in the .reek.yml file in the "detectors:" section are recognized and do work, but custom settings I had under "directories:" in the .reek.yml file were not used. I was able to rework my config file to make everything work with the global "detector:" settings with smart excludes, but it is annoying. To me this seems like it might be an issue kind of like what you see with Rubocop without using the --force-exclusion option.

I'll try and see if I can figure more out in the future, but I do think merging this as-is is definitely an improvement and at least makes the plugin more useful, but there is more work to be done to get the whole .reek.yml file to be used correctly.

**Comment by michaelfranzl** [comment]
I can confirm that this issue still exists. Considering that the fix is so concise (even if it only fixes the `detectors` configuration as @basabin54 reported), could this be merged and released?

**Comment by tommyalvarez** [comment]
@castwide Is this one ready to be approved & merged? I'm eager to have it available and working 😄

**Comment by edward-mb** [comment]
@tommyalvarez Try this ff933718710a4cd354bf2d8963e43745ddbefdb5 I have been using it for months it works. It supports directory specific configurations (directory directives) such as
```yaml
# .reek.yml
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
```
@castwide PR: #2

**Comment by michaelfranzl** [comment]
I tested and can confirm that the patches from @parruda (#1) and @edward-mb (#2) work.

#1 supports only the `detectors` configuration option. #2 adds support for the `directories` configuration option.

However, the support for the `exclude_paths` configuration option is still missing.

My PR #3 is based on #1 and #2 and adds support for the `exclude_paths` configuration option. Reek configuration files should therefore be fully supported.

**Comment by michaelfranzl** [comment]
Hi @castwide , you wrote in https://github.com/castwide/solargraph/issues/388 about this PR:

> I'll merge that PR and publish the new version this week.

This is now over 2 years ago. Is there any chance that this PR could be merged and published as a new gem release? The implementation is complete and it's even tested.

BTW, thank you for Solargraph, it's an essential tool.

**Comment by castwide** [comment]
Sorry for the incredibly long delay. I'll release a new gem today.

**Pull request merged**
